version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
      - ./prompts:/app/prompts
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - wechat_network

networks:
  wechat_network:
    driver: bridge

